"""Transport-neutral TaskController Agent interaction primitives."""

from .audit import audit_event_from_envelope, record_envelope_event
from .continuation import (
    CONTINUATION_MANIFEST_KIND,
    CONTINUATION_PROTOCOL,
    CONTINUATION_STATE_KEY,
    ControllerContinuation,
    ContinuationPhase,
    ContinuationStatus,
    MailboxPollTarget,
    assert_controller_may_finalize,
    bind_continuation,
    continuation_from_envelope,
    persist_before_dispatch,
    persist_continuation,
    recover_continuation,
)
from .envelope import A2A_PROTOCOL, A2AEnvelope, EnvelopeKind, MailboxCursor
from .executor_entrypoint import (
    BOOTSTRAP_BOOTSTRAPPED,
    BOOTSTRAP_RECEIPT_PROTOCOL,
    BOOTSTRAP_STARTED,
    ActiveAttemptFence,
    BootstrapReceipt,
    BootstrapReceiptError,
    EXECUTOR_MAILBOX_BOOTSTRAPPED,
    EXECUTOR_MAILBOX_PROTOCOL,
    ExecutorMailboxRequest,
    MailboxFirstExecutorEntrypoint,
    MailboxReader,
)
from .github_mailbox import mailbox_operation, parse_mailbox_comment, render_mailbox_comment
from .human_projection import HumanEvent, HumanEventKind, project_envelope_for_human
from .wakeup import WAKEUP_PROTOCOL, WakeupSignal

__all__ = [
    "A2A_PROTOCOL",
    "A2AEnvelope",
    "ActiveAttemptFence",
    "BOOTSTRAP_BOOTSTRAPPED",
    "BOOTSTRAP_RECEIPT_PROTOCOL",
    "BOOTSTRAP_STARTED",
    "BootstrapReceipt",
    "BootstrapReceiptError",
    "CONTINUATION_MANIFEST_KIND",
    "CONTINUATION_PROTOCOL",
    "CONTINUATION_STATE_KEY",
    "ControllerContinuation",
    "ContinuationPhase",
    "ContinuationStatus",
    "EXECUTOR_MAILBOX_BOOTSTRAPPED",
    "EXECUTOR_MAILBOX_PROTOCOL",
    "EnvelopeKind",
    "ExecutorMailboxRequest",
    "HumanEvent",
    "HumanEventKind",
    "MailboxCursor",
    "MailboxFirstExecutorEntrypoint",
    "MailboxPollTarget",
    "MailboxReader",
    "WAKEUP_PROTOCOL",
    "WakeupSignal",
    "assert_controller_may_finalize",
    "audit_event_from_envelope",
    "bind_continuation",
    "continuation_from_envelope",
    "mailbox_operation",
    "parse_mailbox_comment",
    "persist_before_dispatch",
    "persist_continuation",
    "project_envelope_for_human",
    "record_envelope_event",
    "recover_continuation",
    "render_mailbox_comment",
]
