"""WP4 execution fabric (NO GWC).

Provider-neutral fabric between WP3 route/receipt and an explicitly injected
binding adapter. Enforces exact request/receipt/lease/fencing correlation before
dispatch, normalizes adapter acks/signals, and hands trusted signals to the WP2
EventRouter without bypassing WP2 authority.

Modules:
- errors: typed ExecutionFabricError hierarchy
- types: runtime-only DispatchEnvelope / DispatchAck / CancelAck / AdapterSignal
- ports: product-neutral ExecutionAdapter port + deterministic FakeExecutionAdapter
- registry: explicit immutable AdapterRegistry (duplicate-key fail-closed)
- fabric / dispatch: dispatch preflight + idempotent dispatch
- signals: AdapterSignal -> canonical AgentEvent -> EventRouter
"""

from __future__ import annotations

from taskcontroller.execution.classification import (
    CLASSIFICATION_SCHEMA_VERSION,
    MAX_LENSES,
    MAX_LENS_LENGTH,
    MAX_PRECONDITIONS,
    MAX_PRECONDITION_LENGTH,
    MAX_PROPOSED_CHILD_COUNT,
    MAX_RATIONALE_LENGTH,
    ExecutionClass,
    ExecutionClassification,
)
from taskcontroller.execution.classifier import (
    ATOMIC_ARTIFACT_LIMIT_BYTES,
    CLASSIFIER_POLICY_SCHEMA_VERSION,
    DEFAULT_COMPLEX_LENSES,
    DEFAULT_CROSS_REVIEW_LENSES,
    DEFAULT_REVIEW_LENSES,
    MAX_ACCEPTANCE_CRITERIA,
    MAX_ACCEPTANCE_CRITERIA_BYTES,
    MAX_ACCEPTANCE_CRITERION_LENGTH,
    MAX_ARTIFACT_SIZE_BYTES,
    MAX_PARENT_CHILDREN,
    ClassifierInput,
    ClassifierPolicy,
    ClassifierPolicyError,
    ExecutionClassificationInput,
    ReviewMode,
    TaskShape,
    classify_execution,
    classify_task,
)
from taskcontroller.execution.child_contract import (
    CHILD_CONTRACT_PROTOCOL,
    ChildContract,
    ChildContractError,
    ChildContractGenerator,
    ChildContractInput,
    ParentContract,
    generate_child_contract,
    generate_child_contracts,
)
from taskcontroller.execution.fanout import (
    FANOUT_COORDINATOR_PROTOCOL,
    MAX_FANOUT_CHILDREN,
    MAX_FANOUT_PARALLEL,
    MAX_STAGE_COUNT,
    ChildCompletion,
    CompletionStatus,
    FanoutCompletion,
    FanoutCoordinator,
    FanoutCoordinatorError,
    FanoutCoordinatorPlan,
    FanoutMode,
    FanoutPlan,
    JoinDecision,
    JoinPolicy,
    JoinStatus,
    NormalizedInputSet,
    NormalizedJoinInput,
    child_completion,
)
from taskcontroller.execution.chunking import (
    CHUNKING_PROTOCOL,
    DEFAULT_MAX_CHUNK_BYTES,
    DEFAULT_MAX_CHUNK_LINES,
    MAX_CHUNK_BYTES,
    MAX_CHUNK_LINES,
    MAX_CHUNKS,
    ChunkJoinDecision,
    ChunkJoinStatus,
    ChunkManifest,
    ChunkPartition,
    ChunkPartitionError,
    ChunkPartitionManifest,
    ChunkPartitioner,
    ChunkRange,
    ChunkRef,
    ChunkedReviewPartitioner,
    partition_chunks,
)
from taskcontroller.execution.errors import (
    AdapterNotFoundError,
    AdapterUnsupportedError,
    DispatchRejectedError,
    DuplicateCommandError,
    ExecutionCorrelationError,
    ExecutionFabricError,
    StaleLeaseError,
)
from taskcontroller.execution.fabric import ExecutionFabric
from taskcontroller.execution.orchestrator import (
    forward_signal_to_router,
    route_and_dispatch,
    signal_to_event,
)
from taskcontroller.execution.ports import ExecutionAdapter, FakeExecutionAdapter
from taskcontroller.execution.registry import AdapterRegistry, build_registry
from taskcontroller.execution.types import (
    AdapterSignal,
    CancelAck,
    DispatchAck,
    DispatchEnvelope,
)

__all__ = [
    "CLASSIFICATION_SCHEMA_VERSION",
    "ATOMIC_ARTIFACT_LIMIT_BYTES",
    "CLASSIFIER_POLICY_SCHEMA_VERSION",
    "DEFAULT_COMPLEX_LENSES",
    "DEFAULT_CROSS_REVIEW_LENSES",
    "DEFAULT_REVIEW_LENSES",
    "MAX_ACCEPTANCE_CRITERIA",
    "MAX_ACCEPTANCE_CRITERIA_BYTES",
    "MAX_ACCEPTANCE_CRITERION_LENGTH",
    "MAX_ARTIFACT_SIZE_BYTES",
    "MAX_PARENT_CHILDREN",
    "MAX_LENSES",
    "MAX_LENS_LENGTH",
    "MAX_PRECONDITIONS",
    "MAX_PRECONDITION_LENGTH",
    "MAX_PROPOSED_CHILD_COUNT",
    "MAX_RATIONALE_LENGTH",
    "ExecutionClass",
    "ExecutionClassification",
    "TaskShape",
    "ReviewMode",
    "ClassifierPolicyError",
    "ExecutionClassificationInput",
    "ClassifierInput",
    "ClassifierPolicy",
    "classify_execution",
    "classify_task",
    "CHILD_CONTRACT_PROTOCOL",
    "ChildContract",
    "ChildContractError",
    "ChildContractGenerator",
    "ChildContractInput",
    "ChildContractFactory",
    "ChildContractSpec",
    "ParentContract",
    "generate_child_contract",
    "generate_child_contracts",
    "create_child_contract",
    "build_child_contract",
    "generate_children",
    "FANOUT_COORDINATOR_PROTOCOL",
    "MAX_FANOUT_CHILDREN",
    "MAX_FANOUT_PARALLEL",
    "MAX_STAGE_COUNT",
    "ChildCompletion",
    "CompletionStatus",
    "FanoutCompletion",
    "FanoutCoordinator",
    "FanoutCoordinatorError",
    "FanoutCoordinatorPlan",
    "FanoutMode",
    "FanoutPlan",
    "JoinDecision",
    "JoinPolicy",
    "JoinStatus",
    "NormalizedInputSet",
    "NormalizedJoinInput",
    "child_completion",
    "CHUNKING_PROTOCOL",
    "DEFAULT_MAX_CHUNK_BYTES",
    "DEFAULT_MAX_CHUNK_LINES",
    "MAX_CHUNK_BYTES",
    "MAX_CHUNK_LINES",
    "MAX_CHUNKS",
    "ChunkJoinDecision",
    "ChunkJoinStatus",
    "ChunkManifest",
    "ChunkPartition",
    "ChunkPartitionError",
    "ChunkPartitionManifest",
    "ChunkPartitioner",
    "ChunkRange",
    "ChunkRef",
    "ChunkedReviewPartitioner",
    "partition_chunks",
    "ExecutionFabricError",
    "ExecutionCorrelationError",
    "AdapterNotFoundError",
    "AdapterUnsupportedError",
    "DuplicateCommandError",
    "DispatchRejectedError",
    "StaleLeaseError",
    "ExecutionAdapter",
    "FakeExecutionAdapter",
    "AdapterRegistry",
    "build_registry",
    "DispatchEnvelope",
    "DispatchAck",
    "CancelAck",
    "AdapterSignal",
    "ExecutionFabric",
    "route_and_dispatch",
    "signal_to_event",
    "forward_signal_to_router",
]
