"""MVP TaskController package (NO GWC, no runtime state, no schema authority).

The active current-main surface contains two small deterministic pieces:

- ``activation``: explicit TaskController mention -> canonical host load plan.
- ``protocol_bridge``: contracted Executor report -> MVP controller verdict.

The richer TaskController core remains a dormant Full-E2E library unless current
repository policy explicitly activates it.
"""

from taskcontroller.mvp.activation import (
    TASKCONTROLLER_ALIASES,
    TaskControllerActivationPlan,
    mentions_taskcontroller,
    resolve_taskcontroller_activation,
)
from taskcontroller.mvp.actions import (
    APPROVE,
    AUTHORITY_ACTIONS,
    CONTROL_ACTIONS,
    FORBIDDEN_DISPOSITIONS,
    INTERNAL_RUNTIME_VERBS,
    MERGE,
    PAUSE,
    PUBLIC_ACTIONS,
    STOP,
    Disposition,
    MvpControlState,
    PublicActionRequest,
    PublicActionResult,
    SafeBoundary,
    SafeBoundaryUnavailableError,
    StaleControlRequestError,
    WorkUnitBlockedError,
    apply_public_action,
    contextual_actions,
    default_safe_boundary,
    start_work_unit,
)
from taskcontroller.mvp.monitoring import (
    BOUNDARY_VERDICTS,
    MATERIAL_REPORT_FIELDS,
    POLL_INTERVAL_SECONDS,
    REASON_BOUNDARY,
    REASON_MAX_POLLS,
    LoopObservation,
    LoopOutcome,
    MalformedReportError,
    ThreadReply,
    material_signature,
    run_monitoring_loop,
)
from taskcontroller.mvp.pilot import (
    AdvancedModeRequired,
    HermesExecutorClient,
    MvpPilot,
    MvpPilotConfig,
    SlackTransport,
    SlackWebApiTransport,
    parse_hermes_reply,
    parse_hermes_thread_update,
    translate_rootcard_to_blocks,
    validate_slack_blocks,
)
from taskcontroller.mvp.protocol_bridge import (
    CONTINUE,
    INTERCEPT,
    PROTOCOL_VERDICTS,
    TERMINAL,
    WAIT_CONTROLLER,
    ContractedSubtask,
    ExecutorReport,
    InterceptReason,
    ProtocolVerdict,
    classify_report,
)
from taskcontroller.mvp.rootcard import (
    COST_VALUES,
    CREATE_ROOT,
    MAX_TASK_CARDS,
    MIN_TASK_CARDS,
    NON_PUBLIC_ACTIONS,
    PUBLIC_ROOTCARD_ACTIONS,
    ROOT_OPS,
    TOKEN_USAGE_UNKNOWN,
    UPDATE_ROOT,
    PlanBlock,
    RootCard,
    RootOp,
    TaskCard,
    TaskCardStatus,
    render_root_op,
    render_rootcard,
)

__all__ = [
    "TASKCONTROLLER_ALIASES",
    "TaskControllerActivationPlan",
    "mentions_taskcontroller",
    "resolve_taskcontroller_activation",
    "CONTINUE",
    "WAIT_CONTROLLER",
    "TERMINAL",
    "INTERCEPT",
    "PROTOCOL_VERDICTS",
    "ContractedSubtask",
    "ExecutorReport",
    "InterceptReason",
    "ProtocolVerdict",
    "classify_report",
    "COST_VALUES",
    "TOKEN_USAGE_UNKNOWN",
    "PUBLIC_ROOTCARD_ACTIONS",
    "NON_PUBLIC_ACTIONS",
    "CREATE_ROOT",
    "UPDATE_ROOT",
    "ROOT_OPS",
    "MIN_TASK_CARDS",
    "MAX_TASK_CARDS",
    "TaskCard",
    "TaskCardStatus",
    "PlanBlock",
    "RootCard",
    "RootOp",
    "render_rootcard",
    "render_root_op",
    "PAUSE",
    "STOP",
    "APPROVE",
    "MERGE",
    "PUBLIC_ACTIONS",
    "CONTROL_ACTIONS",
    "AUTHORITY_ACTIONS",
    "INTERNAL_RUNTIME_VERBS",
    "FORBIDDEN_DISPOSITIONS",
    "Disposition",
    "MvpControlState",
    "PublicActionRequest",
    "PublicActionResult",
    "SafeBoundary",
    "SafeBoundaryUnavailableError",
    "StaleControlRequestError",
    "WorkUnitBlockedError",
    "apply_public_action",
    "contextual_actions",
    "default_safe_boundary",
    "start_work_unit",
    "POLL_INTERVAL_SECONDS",
    "BOUNDARY_VERDICTS",
    "REASON_BOUNDARY",
    "REASON_MAX_POLLS",
    "ThreadReply",
    "LoopObservation",
    "LoopOutcome",
    "MalformedReportError",
    "run_monitoring_loop",
    "MATERIAL_REPORT_FIELDS",
    "material_signature",
    "AdvancedModeRequired",
    "HermesExecutorClient",
    "MvpPilot",
    "MvpPilotConfig",
    "SlackTransport",
    "SlackWebApiTransport",
    "parse_hermes_reply",
    "parse_hermes_thread_update",
    "translate_rootcard_to_blocks",
    "validate_slack_blocks",
]
